-   id: commit-msg-sentiment.py
    name: check for negative sentiment in commit messages
    description: dissalows commits with negative sentiment.
    entry: commit-msg-sentiment.py
    language: python
    stages: [commit, push, manual]