-   id: commit-msg-sentiment
    name: commit-msg-sentiment
    description: 'check commit message sentiment, and reject commit if negative sentiment is detected'
    entry: commit-msg-sentiment
    stages: [commit-msg]
    language: python
    require_serial: false
    additional_dependencies: [textblob, afinn]
    fail_fast: true
    minimum_pre_commit_version: '3.2.0'
