-   id: commit-msg-sentiment.py
    name: commit-msg-sentiment.py
    description: 'check commit message sentiment, and reject commit if negative sentiment is detected'
    entry: commit-msg-sentiment.py
    language: python
    'types': [python]
    require_serial: false
    additional_dependencies: [textblob, afinn]
    always_run: true
    fail_fast: true
    stages: [commit-msg]
    minimum_pre_commit_version: '3.2.0'
